import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Navbar from "@/components/main/navbar-top";
import { ThemeProvider } from "@/components/ui/theme-provider";
import DockFooter, { links } from "@/components/main/dock-footer";
import CanvasCursor from "@/components/ui/canvas-cursor";
import CustomCursor from "@/components/ui/cutom-cursor";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider attribute="class" defaultTheme="dark">
          <Navbar items={links} />
          <div className="md:pb-24">{children}</div>
          <div className="md:fixed md:bottom-0 fixed bottom-[10vh] left-5 md:left-0 w-full z-[100]">
            <DockFooter />
          </div>
          <CanvasCursor />
          <CustomCursor />
        </ThemeProvider>
      </body>
    </html>
  );
}
